version: '3'
services:
  grafana:
    image: grafana/grafana-enterprise   # 开源版 image: grafana/grafana
    container_name: grafana
    volumes:
      - /data/grafana/storage:/var/lib/grafana
    ports:
      - 3000:3000
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/config:/etc/prometheus/config
    ports:
      - 9090:9090
    labels:
      org.label-schema.group: "monitoring"
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - 9091:9091
    restart: always

  # 监控节点
  # node-exporter:
  #   image: prom/node-exporter
  #   container_name: node-exporter
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   ports:
  #     - 9100:9100
  #   environment:
  #     TZ: Asia/Shanghai
  #   # command:
  #   #   - '--path.procfs=/host/proc'
  #   #   - '--path.rootfs=/rootfs'
  #   #   - '--path.sysfs=/host/sys'
  #   #   - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
  #   labels:
  #     org.label-schema.group: "monitoring"
  #   restart: always
  #   network_mode: host

  # 监控docker所需的cadvisor
  # cadvisor:
  #   image: google/cadvisor
  #   container_name: cadvisor
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:rw
  #     - /sys:/sys:ro
  #     - /var/lib/docker:/var/lib/docker:ro
  #     - /dev/disk/:/dev/disk:ro
  #     - /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
  #   ports:
  #     - 9101:8080
  #   environment:
  #     TZ: Asia/Shanghai
  #   labels:
  #     org.label-schema.group: "monitoring"
  #   restart: always

  # 监控mongo所需的mongo_exporter (Grafana Dashboard: 20867)
  mongo_exporter:
    image: percona/mongodb_exporter:0.43.1-amd64
    container_name: mongo_exporter
    ports:
      - 9216:9216
    restart: always
    environment:
      MONGODB_URI: "mongodb://monitor:monitor@192.168.100.24:27017/admin?connectTimeoutMS=10000&ssl=false"
    command:
      - '--collect-all'
      - '--compatible-mode'
      - '--mongodb.collstats-colls=test'